import { Geist, Geist_Mono,  Space_Grotesk} from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const space_grotesk = Space_Grotesk({
    weight: ["300", "400", "500", "600", "700"], // choose weights you need
    subsets: ["latin"],
});


export const metadata = {
  title: "CookMateAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${space_grotesk.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
